### ISSUE TITLE
"Optimize image" context menu option causing a fatal error

### ISSUE THREAD

**Issue by c4rlosmarin** [madskristensen/ImageOptimizer#17]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 1
- This extension: 3.4.60
### Description

Each time i try to optimize an image, Visual Studio crashes and I get the following error messages on Event Viewer:

<img width="265" alt="crash" src="https://cloud.githubusercontent.com/assets/17365297/13199532/65755ede-d7f6-11e5-9073-53b690bf216c.png">

<img width="961" alt="eventviewer1" src="https://cloud.githubusercontent.com/assets/17365297/13199519/c447cd3a-d7f5-11e5-9166-677f72eb6a1c.png">

<img width="962" alt="eventviewer2" src="https://cloud.githubusercontent.com/assets/17365297/13199522/ede5bca6-d7f5-11e5-9200-600331711a99.png">
### Steps to recreate
1. Right-Click an image on Solution Explorer
2. Select the "Optimize image" context menu option 
### Current behavior

Visual Studio crashes and errors are being registered on Event Viewer:
### Expected behavior

Optimize the image and show the detailed output from the optimization process

**Comment by c4rlosmarin** [comment]
The same happens when I try to optimize all images from a folder.

**Comment by madskristensen** [comment]
It should be fixed in the latest CI build

**Comment by madskristensen** [comment]
CI build http://vsixgallery.com/extension/bf95754f-93d3-42ff-bfe3-e05d23188b08/

**Comment by c4rlosmarin** [comment]
It's now working ok on build 3.4.66.

Great work, keep it up!    :-)
