### ISSUE TITLE
Feature Request: SVG Optimizer

### ISSUE THREAD

**Issue by coliff** [madskristensen/ImageOptimizer#19]
Love this extension for bitmap images. Would love to see support for optimising SVG built-in.

**Comment by Nettsentrisk** [comment]
Implementing SVGO to optimize SVGs should be a no-brainer :)

**Comment by JavierCanon** [comment]
1. https://github.com/svg/svgo
2. https://hacks.mozilla.org/2015/03/optimising-svg-images/

the simple method is minify and remove unused data from de xml (svg), the web server ex. IIS can compress the .svg files with zip

**Comment by markvantilburg** [comment]
Compressor.cs

Change supported list to:
`private static readonly string[] _supported = { ".png", ".jpg", ".jpeg", ".gif", ".svg" };`

Inside this method add svg option:
private static string GetArguments(string sourceFile, string targetFile, bool lossy)

`                case ".svg":
                    {
                        return $"/c npx svgo \"{sourceFile}\" -o \"{targetFile}\"";
                    }`

But the user would need to have npm / npx and svgo installed for this to work

@madskristensen do you have an idea?

**Comment by madskristensen** [comment]
@markvantilburg In the vast majority of cases, they won't have those npm packages installed globally

**Comment by markvantilburg** [comment]
I see the old web compiler includes node js packages for compiling less files, could that be an option for this plugin? I could not find a .exe file to compress svg files.

**Comment by markvantilburg** [comment]
This apose.SVG needs a license, and as such tags the images with a banner that a license is required, it also did not optimize the svg correctly:
ORIGINAL
![avv-logo-ORIGINAL](https://github.com/user-attachments/assets/77dd3ff0-ed26-4061-8269-c938b16a1ffd)
OPTIMIZED
![avv-logo-OPTIMIZED](https://github.com/user-attachments/assets/58cbc5a6-6f29-4bb7-b750-dd199f8e8f4c)

[avv logo.zip](https://github.com/user-attachments/files/17916055/avv.logo.zip)

**Comment by madskristensen** [comment]
@markvantilburg yikes, that's no good. I'll find another optimizer. Do you know of any?

**Comment by HugoVG** [comment]
I used the standard [svgo](https://github.com/svg/svgo) package and wrapped it with [bun](https://bun.sh/), sadly this comes with a big unzipped size(108mb) and (relatively) large gzipped size(38mb)

<details>
<summary>How I made it</summary>
# sv-go-buns

install bun:

```bash
npm install -g bun
```

Initialize bun workspace (like dotnet new)

```bash
bun init
```


To install dependencies:

```bash
npm install svgo
```

To run:

```bash
bun run index.ts
```

Building:

index.ts file

```ts
//Index.ts

import { optimize } from 'svgo';

if(Bun.argv[2] === null){
    console.log("Positional Input 'Entry' is not set");
    process.exit(-1)
}
if(Bun.argv[3] === null){
    console.log("Positional Input 'Output' is not set");
    process.exit(-1)
}

const file = Bun.file(Bun.argv[2]);
const text = await file.text();

const result = optimize(text, {
    path: Bun.argv[1],
    multipass: true,
});
await Bun.write(Bun.argv[3], result.data);
process.exit(0);

```

building: 
```bash
bun build --compile --target=bun-windows-x64  --minify --sourcemap  .\index.ts --outfile svgobuns
``` 

running:
```bash
.\svgobuns.exe .\test.svg out.svg
```
9kb -> 7kb

</details>

Sadly couldn't find any C#/dotnet native things 🥲

**Comment by markvantilburg** [comment]
@madskristensen, I suppose it would be great to use the standard `svgo` packed into an .exe, as suggested by @HugoVG above, since it seems that `svgo` is the only good working tool out there.

**Comment by madskristensen** [comment]
@markvantilburg @HugoVG it would be fantastic to be able to use svgo, but I think 38 mb is over the top for an extension like this. It's surprising that I can't even find a C++ optimizer that can be used from .NET

**Comment by aloksharma1** [comment]
> @markvantilburg @HugoVG it would be fantastic to be able to use svgo, but I think 38 mb is over the top for an extension like this. It's surprising that I can't even find a C++ optimizer that can be used from .NET

ok , here is an idea is C++ really necessary; can you try rust or other languages-based libraries which are in similar efficiency? i found this for dotnet https://github.com/dabutvin/SvgClean buts it's a dead repo (last updated 5 years ago)
but in rust i found [svgo-rs](https://github.com/svg-rust/svgo-rs) probably worth a look.
also go lang based minify [minify](https://github.com/tdewolff/minify/tree/master/cmd/minify)

**Comment by madskristensen** [comment]
@aloksharma1 I tried SvgClean, but it doesn't really work
