### ISSUE TITLE
Could this be a Turned into a NuGet package?

### ISSUE THREAD

**Issue by RehanSaeed** [madskristensen/ImageOptimizer#21]
I'm looking for an Image optimization package to call from C#. NodeJS has some very nice tools in this area. Could the optimization engine be turned into a NuGet package?

**Comment by madskristensen** [comment]
Yes, it totally could.

**Comment by sallgeud** [comment]
Would you mind if we turned this into a basic ImageOptimizer library and GUI for bulk optimizing outside of Visual Studio, using the same methods you've done (which are better than others)?  Then have this reference at least that shared library (for which we could share access)? We've been using PNGGauntlet (for PNG only) for a while, and then making fake VS projects to accomplish bulk optimization for the others with your tool.  A gui for it would be so much better, and you've already got all the important bits done here.

**Comment by madskristensen** [comment]
Go for it

**Comment by itorian** [comment]
Just started using @madskristensen implementation in MVC project here https://github.com/itorian/ImageOptimizerOrCompressor
