### ISSUE TITLE
Extension causes 10-15 second lock up on solution context menu

### ISSUE THREAD

**Issue by mip1983** [madskristensen/ImageOptimizer#22]
### Installed product versions
- Visual Studio: 2015 Professional 14.0.25422.01 Update 3
- Image Optimizer 3.6.89 (installed with the web extension pack)
### Description

Visual studio hangs (often with 'not responding' at the top of the window) for 10-15 seconds on the right-click context menu in solution explorer and 15-20 seconds on the 'Image optimizer' menu. It is a very large solution with a lot of projects (not sure if that's related to the amount of delay).
### Steps to recreate
1. Enable the 'Image Optimizer' extension.
2. Right click on the solution in solution explorer.
3. After recoving from the initial 10-15 second hang with VS not responding, if you go to the 'Image optimizer' context menu item, it also hangs if you click this item for 15-20 seconds before the sub menu appears.
### Current behavior

Visual studio now hangs (often with 'not responding' at the top of the window) for 10-15 seconds on solution explorer context menu and 15-20 seconds on the 'Image optimizer' menu as described above.
### Expected behavior

Not hanging, context menu loads instantaneously with no delay after right click.

**Comment by mvaneijk** [comment]
I can confirm this issue. I have a solution with 9 C++ projects. Often, the context-menu does not open.
