### ISSUE TITLE
Review count discrepancy

### ISSUE THREAD

**Issue by GregTrevellick** [madskristensen/ImageOptimizer#26]
### Installed product versions
- Visual Studio: n/a
- This extension: 3.6.94

### Description
The 'REVIEWS' count for this extension says "(57)" but the "REVIEWS" tab says "(55)".

This may not be an issue with this specific extension, possibly an issue with the VS gallery perhaps, but I'm not sure where to log the apparent bug, so for now I'll log here but happy to move it elsewhere if appropriate.

### Steps to recreate
1. Visit https://visualstudiogallery.msdn.microsoft.com/a56eddd3-d79b-48ac-8c8f-2db06ade77c3 (in Chrome or IE11, and probably the same issue in all browsers)
2. Check the two review counts as per screen shot below
![image](https://cloud.githubusercontent.com/assets/13434709/20002438/c9e7808e-a278-11e6-89e4-ba80161f8a97.png)

**Comment by madskristensen** [comment]
This is an issue in Visual Studio and/or the Extension Gallery. It cannot be fixed by this extension

**Comment by GregTrevellick** [comment]
No problem - I will post to VS Gal. issues 🤓
