### ISSUE TITLE
Lossy optimize image removed all image bytes (Saving 100%)

### ISSUE THREAD

**Issue by itorian** [madskristensen/ImageOptimizer#27]
Hi @madskristensen 
Thanks for the awesome extensions you create that saves huge time.
I'm using these extensions from the very first version you introduced years back but today I noticed 100% saving on JPG image and turned file size 0. As usual, I right clicked on 'images' folder | Image Optimizer | Lossy Optimize Images. Here's the output in Visual Studio 2015 Update 3:

![100-percent-saved](https://cloud.githubusercontent.com/assets/3646552/20135466/d1fd8bc6-a695-11e6-8401-f2f0f0ad70bd.png)

In case you need the image file, here's the one:

![course_thumbnail_default](https://cloud.githubusercontent.com/assets/3646552/20135468/d36403fa-a695-11e6-9f97-1684f6664ca8.jpg)

**Comment by ChuKhaLi** [comment]
Same issue. Some of my images become 0 after lossy compress. Here is the output from VS 2015
```
12/23/2017 9:32:12 PM: Optimized ban-ra-chuan-mitutoyo-517-114c.jpg in 0.15 seconds
Before: 185061 bytes
After: 0 bytes
Saving: 185061 bytes / 100%
12/23/2017 9:32:15 PM: Optimized de-ga-panme-mitutoyo-156-101-10.jpg in 0.1 seconds
Before: 179471 bytes
After: 0 bytes
Saving: 179471 bytes / 100%
12/23/2017 9:32:15 PM: Optimized dong-ho-do-do-day-mitutoyo-547-321.jpg in 0.15 seconds
Before: 139851 bytes
After: 0 bytes
Saving: 139851 bytes / 100%
12/23/2017 9:32:12 PM: Optimized ban-ra-chuan-mitutoyo-517-114c.jpg in 0.15 seconds
Before: 185061 bytes
After: 0 bytes
Saving: 185061 bytes / 100%
12/23/2017 9:32:15 PM: Optimized de-ga-panme-mitutoyo-156-101-10.jpg in 0.1 seconds
Before: 179471 bytes
After: 0 bytes
Saving: 179471 bytes / 100%
12/23/2017 9:32:15 PM: Optimized dong-ho-do-do-day-mitutoyo-547-321.jpg in 0.15 seconds
Before: 139851 bytes
After: 0 bytes
Saving: 139851 bytes / 100%
```
This is one of my image
![ban-ra-chuan-mitutoyo-517-114c](https://user-images.githubusercontent.com/15166543/34320343-b57348ec-e82a-11e7-851c-b19024a02a95.jpg)
