### ISSUE TITLE
Installation issue against VS 2017 RC

### ISSUE THREAD

**Issue by kymikoloco** [madskristensen/ImageOptimizer#30]
### Installed product versions
- Visual Studio 2017 RC Professional 
- This extension: 3.6.103

### Description
I installed this extension for 2013 and 2015, but it does not recognize 2017 RC as a possible install target.

### Current behavior
Will not install to 2017

### Expected behavior
Should be able to install to the VS 2017 Professional RC.

**Comment by lruckman** [comment]
Even installing through the Extensions and Updates menu item under Tools in the latest 2017 RC doesn't help.

**Comment by lruckman** [comment]
The extension works if you install from within VS 2017 RC from _Tools > Extensions and Updates_ menu

**Comment by madskristensen** [comment]
Fixed
