### ISSUE TITLE
Can this be used inside mvc or .net Core

### ISSUE THREAD

**Issue by aloksharma1** [madskristensen/ImageOptimizer#31]
hello,

i would like to know if this project can be turned into a dll to be used inside web projects. something like passing a list of file paths creating optimized images and with option[bool param] of preserving old files by renaming them to filename-old.ext to same place or provided path.

thanks

Edit: this will save a lot of round trip & ftp we need to do these days using pagespeed.

**Comment by dlemstra** [comment]
Maybe you could use the `ImageOptimizer` from my [Magick.NET](https://github.com/dlemstra/Magick.NET) project for this. The .NET core version only works on Windows at the moment and I don't know if the compression is as great as the tools used by this project. But I have used it myself to resolved the issues reported by PageSpeed Insights.

**Comment by itorian** [comment]
Yes you can, that's what I started using https://github.com/itorian/ImageOptimizerOrCompressor. This uses exact same way this ImageOptimizer work, you get both optimization options, best quality and best compression.

**Comment by aloksharma1** [comment]
> Yes you can, that's what I started using https://github.com/itorian/ImageOptimizerOrCompressor. This uses exact same way this ImageOptimizer work, you get both optimization options, best quality and best compression.

i am surely going to try this one, thanks a lot

**Comment by madskristensen** [comment]
If your web app is hosted on Azure, just add [this NuGet package](https://www.nuget.org/packages/Azure.ImageOptimizer/) to your project and forget about it. All images currently on the site and all future images being uploaded will automatically be optimized
