### ISSUE TITLE
Use Google guetzli instead of jpegtran

### ISSUE THREAD

**Issue by al1b** [madskristensen/ImageOptimizer#32]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: 3.6.103

### Description
ImageOptimizer is using `jpegtran` for lossless compression of `JPEG` images. It's been a while Google has released it's [*Perceptual JPEG encoder guetzli*](https://github.com/google/guetzli). The result of `guetzli` is really better than other compressors. As it says it could compress to 35% more than the other compressors.

**Comment by JavierCanon** [comment]
> 
> ### Installed product versions
> 
>     * Visual Studio: 2017 Community
> 
>     * This extension: 3.6.103
> 
> 
> ### Description
> 
> ImageOptimizer is using `jpegtran` for lossless compression of `JPEG` images. It's been a while Google has released it's [_Perceptual JPEG encoder guetzli_](https://github.com/google/guetzli). The result of `guetzli` is really better than other compressors. As it says it could compress to 35% more than the other compressors.

No since for the most people guetzli is too heavy to RAM and CPU, it's kinda dead. The only people that could help you are Google employees and they don't work on guetzli anymore.

**Comment by madskristensen** [comment]
I've tried it and it takes 10 minutes to run on a single image. It's not suitable for an extension like this. The end result of using it was great though
