### ISSUE TITLE
VS Code Support

### ISSUE THREAD

**Issue by jcphlux** [madskristensen/ImageOptimizer#36]
I would Love to have this tool in VS Code.
I have been debating trying to write my own but love ImageOptimizer.

**Comment by LeeCoder139** [comment]
I would love to see this tool added to VSCode as well

**Comment by pankaj-nikam** [comment]
+1

**Comment by madskristensen** [comment]
That's out of scope for this extension project, since the extensibility model for VS Code is completely different
