### ISSUE TITLE
#ask: this project can't open on vs2013

### ISSUE THREAD

**Issue by tanvan81** [madskristensen/ImageOptimizer#38]
Hi

I'v working on vs 2013, So this project cann't open ???

When I read 
"For cloning and building this project yourself, make sure to install the Extensibility Tools 2015 extension for Visual Studio which enables some features used by this project."

That's meen we need install Extensibility Tools 2015

Tks

**Comment by madskristensen** [comment]
Yes, you need VS 2015 or 2017
