### ISSUE TITLE
Gif optimizer resizes the image

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/ImageOptimizer#4]
Original:

![hline](https://cloud.githubusercontent.com/assets/4510245/7294612/13602eb6-e9af-11e4-9d06-0f19c755feb7.GIF)

Optimized:

![hline](https://cloud.githubusercontent.com/assets/4510245/7294631/5108d9e8-e9af-11e4-8cf4-8b15d92eb3d9.GIF)

Maybe there can be a setting to enable/disable resizing of gif images if possible.

**Comment by madskristensen** [comment]
That is very odd. Perhaps it's due to high DPI values. Can you send me the original image by email to post at madskristensen net?

**Comment by tnx247** [comment]
I have the same issues. Please check for the original image in the link above, its in size 70x30. And after optimize, its 70x9

**Comment by madskristensen** [comment]
Yikes. I'll need to fix this. Can you please link to the image so I can reproduce the bug?

**Comment by tnx247** [comment]
hi Mad,
gif to test: https://cloud.githubusercontent.com/assets/4510245/7294612/13602eb6-e9af-11e4-9d06-0f19c755feb7.GIF

**Comment by madskristensen** [comment]
Fixed
