### ISSUE TITLE
DPI values are lost after optimization

### ISSUE THREAD

**Issue by cpCr4zy** [madskristensen/ImageOptimizer#41]
### Description
All optimizations on the image reset the dpi. But it very important to keep the original value, because it will be used in WPF

### Steps to recreate
1. Get jpeg/png file with custom DPI values
2. Optimize

### Current behavior
The DPI value is lost or set to default 96 dpi.

### Expected behavior
The DPI value keep original value

**Comment by madskristensen** [comment]
Should be fixed now with the latest pingo executable
