### ISSUE TITLE
Cannot find extentions in Visual code + extension/package.json not found inside zip.

### ISSUE THREAD

**Issue by Benoit1980** [madskristensen/ImageOptimizer#42]
Visual Studio:
Version: 1.27.2 (user setup)
Commit: f46c4c469d6e6d8c46f268d1553c5dc4b475840f
Date: 2018-09-12T16:17:45.060Z
Electron: 2.0.7
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Hello,

I have 2 issues with your extenstion:

1)I cannot find it in the search extension of Visual Code(It does not exists anymore).

2)When I download it from here:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ImageOptimizer

And try to install it via the visual code "Install from VSIX", I get this error:
"extension/package.json not found inside zip."

Any idea why please?

Thank you.

**Comment by madskristensen** [comment]
This is a Visual Studio extension - it doesn't work on Visual Studio Code

**Comment by Benoit1980** [comment]
My apology.... Thank you for the reply.
