### ISSUE TITLE
Chocolatey Install Issue - No CheckSum by default

### ISSUE THREAD

**Issue by spcope** [madskristensen/ImageOptimizer#43]
### Installed product versions
- Powershell
- Chocolatey v.0.10.13

### Description
Trying to install this package using Chocolatey and getting an error because there is no checksum value by default. It is erroring out saying that 'Empty checksums are no longer allowed by default for non-secure sources.' Would prefer to not use the --allow-empty-checksums command without needing too.

### Steps to recreate
1. Open powershell
2. Install chocolatey
3. choco install imageoptimizer

**Comment by madskristensen** [comment]
I'm not doing Chocolatey anymore
