### ISSUE TITLE
BUG: Image Optimizer menu item command missing from context menu for image file

### ISSUE THREAD

**Issue by Bartolomeus-649** [madskristensen/ImageOptimizer#44]
### Installed product versions
- Microsoft Visual Studio Professional 2019 Preview Version 16.4.0 Preview 4.0
- This extension: 4.0.132

### Description
The image Optimizer context menu item command is missing when right clicking n image file

### Steps to recreate
1. Open a folder containing images (File->Open->Folder...)
2. Right click an image in solution explorer
3. The "Image Optimizer" command is missing from the context menu.

![image](https://user-images.githubusercontent.com/7513795/68870416-237a5880-06fb-11ea-986d-680859984fec.png)

**Comment by nietras** [comment]
Yes it seems this is missing when opening a folder directly and not a solution.

**Comment by Christopher-CO** [comment]
> Yes it seems this is missing when opening a folder directly and not a solution.

I'm also getting this issue, even though I'm opening a solution.

**Comment by pramadito** [comment]
![Screenshot 2021-11-12 103605](https://user-images.githubusercontent.com/13034156/141405692-1138e791-d5d7-4b5a-95e4-99bd196e9435.png)
it's still missing in newer visual studio 2019 community version
