### ISSUE TITLE
extension/package.json not found inside zip.

### ISSUE THREAD

**Issue by pleabargain** [madskristensen/ImageOptimizer#45]
### Installed product versions
$code --install-extension Image_Optimizer_v4.0.132.vsix 
Installing extensions...
extension/package.json not found inside zip.
Failed Installing Extensions: Image_Optimizer_v4.0.132.vsix

Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T15:51:39.791Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic snap

Here's a screen grab.
https://i.imgur.com/NxFniKu.png
There are 2 json. Maybe the bug is on Version: 1.47.3

I tried with another app and got the same error.

**Comment by madskristensen** [comment]
This is an extension for Visual Studio and not for VS Code. The extension format between the two are not compatible
