### ISSUE TITLE
How to use this with VS 2022

### ISSUE THREAD

**Issue by Otto404** [madskristensen/ImageOptimizer#48]
### Installed product versions
Could not install in VS 2022

### Description
I would like to uses the ImageOptimizer in VS 2022

### Steps to recreate
1. I downloaded the installer

### Current behavior
It says: "Install with VS 2019" 

### Expected behavior
"Install with VS 2022"

**Comment by markvantilburg** [comment]
The 64bit version works in 2022:
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ImageOptimizer64bit
