### ISSUE TITLE
Update gifsicle to v1.95

### ISSUE THREAD

**Issue by markvantilburg** [madskristensen/ImageOptimizer#52]
Current version installed is:

```
Resources\Tools> .\gifsicle.exe --version
LCDF Gifsicle 1.92
Copyright (C) 1997-2019 Eddie Kohler
```

According to the website
[https://www.lcdf.org/gifsicle/](https://www.lcdf.org/gifsicle/)

There are newer versions available:
```
1.95 19.Feb.2024
Fix some bugs.

1.94 23.Jun.2023
Fix some bugs.

1.93 30.Jun.2021
Fix security bug on certain resize operations with ‘--resize-method=box’.
Fix problems with colormapless GIFs.
```

The command line parameters are still the same so this would be a simple replace of the .exe

**Comment by markvantilburg** [comment]
I see that there are special builds for 32/64 and arm available;
https://eternallybored.org/misc/gifsicle/

It might be an idea to load all 3 versions and make the extension aware of which exe to call?

**Comment by madskristensen** [comment]
We only need the 64bit because VS 2022 itself only runs on 64bit, so it's guaranteed to always run in that context.
