### ISSUE TITLE
Increasing file size : optipng vs pngout

### ISSUE THREAD

**Issue by biovolt** [madskristensen/ImageOptimizer#8]
First of all thank you for ImageOptimizer !!!!

I have a lot of png's that I optimized using optipng.exe  -o7 -strip all Filename.png.
Source : http://www.thewebflash.com/2014/05/how-to-optimize-jpeg-png-images-using.html

Now that you have put in all the effort to rewrite it (Thank you !) I ran it to compare the results and found this.

2015-05-04 14:50:07: Optimized confirmation.png
Before: 1341 bytes
After: 1432 bytes
Saving: -91 bytes / -6.8%

2015-05-04 14:50:07: Optimized homeLoanImage.jpg
Before: 44656 bytes
After: 44656 bytes
Saving: 0 bytes / 0%

2015-05-04 14:50:07: Optimized brochure_bathrooms.png
Before: 162 bytes
After: 212 bytes
Saving: -50 bytes / -30.9%

2015-05-04 14:50:07: Optimized brochure_bedrooms.png
Before: 160 bytes
After: 223 bytes
Saving: -63 bytes / -39.4%

2015-05-04 14:50:07: Optimized brochure_garages.png
Before: 229 bytes
After: 307 bytes
Saving: -78 bytes / -34.1%

Could you please have a look into why the image size was increased instead of reduced? 
I do understand that you provide a interface and did not develop the tools : optipng vs pngout  
Perhaps you can build in a check to only replace the image if the size was actually reduced ?

**Comment by madskristensen** [comment]
I don't think it writes the larger file to disk, but I'll take a look

**Comment by madskristensen** [comment]
Can you please share one of the PNGs that resulted in a larger file?

**Comment by madskristensen** [comment]
Can you please try the new build located here http://vsixgallery.com/extension/bf95754f-93d3-42ff-bfe3-e05d23188b08/
